# Generated by Django 3.2 on 2021-07-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='territory',
            field=models.CharField(default='Uzbekistan', max_length=30),
        ),
    ]
