# Generated by Django 3.2 on 2021-07-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_territory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.territory'),
        ),
    ]
