# Generated by Django 3.2 on 2021-07-25 03:59

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_territory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='territory',
            field=models.ForeignKey(default=account.models.get_territory, on_delete=django.db.models.deletion.CASCADE, to='account.territory'),
        ),
    ]
