# Generated by Django 3.2 on 2021-07-25 05:39

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_territory'),
        ('blog', '0005_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='territory',
            field=models.ForeignKey(default=blog.models.get_territory, on_delete=django.db.models.deletion.CASCADE, to='account.territory'),
        ),
    ]
